#url: https://jackbinysh.github.io
#baseurl: /wedding-website/
url: https://jackandbecky.co.uk
baseurl:

# Site settings
title: "#JECKY2022"
email: jack.binysh@gmail.com
description: "Jack Binysh and Becky Knott are getting married in Oxford on June 25, 2022"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3dbbf0
  secondary: 2f90b9  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    #  - title: twitter
    #url: http://twitter.com/apretz

# Build settings
markdown: kramdown
permalink: pretty
